### ISSUE TITLE
"Create channels file" crashes the MeTV

### ISSUE THREAD

**Issue by tomidis** [Me-TV/Me-TV#10]
I have channels file created with dvbv5, but anyway, I was curious about "Create channels file" option, so when I start it, the app closes. The same behavior was before I had the channels file.

**Comment by russel** [comment]
The original Me TV  used the Linux API directly to manage the DVB devices and had a section devoted to tuning. It was though DVBv3. Rather than rewrite that code for for DVBv5 in Rust, Me TV 3 is making the assumption that the executable dvbv5-scan (from the dvb-tools package on Debian Sid) is present and calls that in a subprocess.

If the problem here is the lack of this executable, then Me TV is failing incorrectly and that needs fixing.

If the problem is something to do with actually running the executable, then more investigation is needed.

**Comment by tomidis** [comment]
If it helps, output of:
`GST_DEBUG=3 me-tv`
after click on the "Create channels file", gives the following one line:
`thread 'main' panicked at 'assertion failed: path.is_dir()', src/transmitter_dialog.rs:46:5`

**Comment by russel** [comment]
I think this a case of another missing package, and thus a hint that more set up help is needed in the README. Creating a channels file requires the transmitter files which are in the package dtv-scan-tables.

**Comment by russel** [comment]
I have update the README which hopefully helps not get to this point. I will extend the code to be friendlier when it does happen.

**Comment by russel** [comment]
I believe changeset https://github.com/Me-TV/Me-TV/commit/793d21a3907cd1570d0fb16df1249a98ee46d71b should make the behaviour of Me TV very much better in the situation where the transmitter files cannot be found. This is currently untested – which is clearly a bit bad, untested code is not good code.

**Comment by tomidis** [comment]
I just tested the new compile
There is no more an app crash, but the window with message

> There appear to be no transmitter files,
> perhaps the dvb-scan-tables package is not installed.

**Comment by russel** [comment]
Splendid. At least that worked. However, I think a reworking of the code is needed, as there is a bit of an irritant and bad design in the currrent code. I shall do a change, but this time test it before committing it!

**Comment by russel** [comment]
I have made some amendments, and given them a bit of a test, so I think this issue can now be closed.

If there are still problems, best to create new issues to track them.
