### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tomidis** [Me-TV/Me-TV#2]
Hi
I'm relative new to linux (using it about 1 year), so I'm still struggling with installations and settings.
Recently I switched from Mint 18.3 to 19
Original MeTV cannot be installed on Mint 19 (or I don't know how to install it), so I found this fork.
First I had a lot of problems until I managed to install this fork.
In the end, I found out that the problem was in old cargo/rust version (1.25) which in installed using mint software manager. After installing last version (1.29) using: "curl https://sh.rustup.rs -sSf | sh", then I managed to install this fork (but I also needed to install some missing dependencies: libgtk2.0-dev, libgstreamer1.0-dev, libgtk-3-dev).
Finally I also managed to create the channels file using dvbv5.
Now when I start the MeTV frontend, I get two buttons "adaptor0 frontend0" and "adaptor1 frontend0". Bellow every button is channels list.
No matter which channel I select, when I click on the adaptor button, the Me TV closes itself and nothing happens further.
My TV card is not USB, but PCI-E one: Terratec Cinergy T PCIE Dual
Need some help!
tomi

**Comment by russel** [comment]
Mint is based on Ubuntu, which in turn is based on Debian. Whilst Debian Sid still has me-tv 1.3.7, Ubuntu has chosen not to stock it since Xenial 16.04, which means the new Mints do not have the me-tv package. I am hoping to get me-tv 3.0 in as a replacement for me-tv 1.3.7 into Debian Sid, in which case it might re-appear in Ubuntu and thence Mint.

Ubuntu, and thus Mint, seem not to be tracking upgrades in Rust as Debian Sid is. This is sad, but using the Rustup system is the way forward. It is what I do even on Debian Sid. Of course this raises the issue that only developers should have to do this, users should be able to download pre-compiled executables. The issue is how to get this done in an automated way. I have created Issue #3 to track this point.

Creating the necessary GStreamer channels file is something that has to be done, and it has to be done for every change of venue, and on a regular basis anyway as the transmitters often reshuffle the channels in the multiplexes. This needs to be made as simple as possible, but what is currently there clearly is not as simple as possible. Perhaps @tomidis you could create a separate issue for this point so that we can make the user experience (UX) much better.

I am so glad I chose to use filestore watching to get the DVB device status now. I use only USB devices and so was tempted to do USB device checks. I had failed to appreciate that some people have PCI-E cards. So by design^H^H^H^H^H^Hluck the system has coped with the different hardware correctly.

So let's restrict this issue to getting what you have in place working and any other problems create new   issues.

**Comment by russel** [comment]
That the main screen comes up with two adapters means the hardware side of things seems to be working. Me TV assumes all the GStreamer and Linux kernel drivers handle all hardware issues, that as long as the special files are present in /dev/dvb everything will work.

The hypothesis has to be that some form of exception is being thrown and yet not being reported. What would be good is to run the code in debug mode and see what gets reported. Given that the most likely suspect is missing GStreamer plugins, the best bet is to tackle that first. @tomidis can I get you to try using the command line:
```
GST_DEBUG=3 me-tv
```
when you try to start a channel this should result in lots and lots of output. If the terminal is colourising then it is the red error report we are looking for.

**Comment by tomidis** [comment]
This is the whole output:
`0:00:00.019599591  1815 0x55ca61fd7520 ERROR                default gstvaapi.c:254:plugin_init: Cannot create a VA display
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
0:00:43.691335606  1814 0x7f2afb146600 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "gtkglsink"!
0:00:43.691387577  1814 0x7f2afb146600 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "gtksink"!
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21`

**Comment by russel** [comment]
I think we have the problem, well at least the one causing this problem. For various reasons, the GTK plugin for GStreamer got separated out from the good/bad/ugly plugin sets into its own package on Debian. This means Ubuntu (post bionic) and thus Mint as well. I would expect that installing the package will solve this problem:
```
aptitude install gstreamer1.0-gtk3
```

**Comment by tomidis** [comment]
It's working!!!!!! :-)

**Comment by russel** [comment]
Splendid stuff.

Thank you for getting stuck into this and persevering. 

If you think changes to the README, or pages on the wiki, are needed to help people coming new to this version of Me TV, please feel free to put your experience down as an aid to others.

**Comment by tomidis** [comment]
Well thank you for your effort to keep this app alive.
I think it would be nice if you put a word or two about Rust version and GStreamer plugins in a README file.

**Comment by russel** [comment]
I believe this issue has now served it's purpose so it is time to close it. I am sure there are other bugs and enhancements but I think they deserve their own issues!

**Comment by dougK44883** [comment]
> Mint is based on Ubuntu, which in turn is based on Debian. Whilst Debian Sid still has me-tv 1.3.7, Ubuntu has chosen not to stock it since Xenial 16.04, which means the new Mints do not have the me-tv package. I am hoping to get me-tv 3.0 in as a replacement for me-tv 1.3.7 into Debian Sid, in which case it might re-appear in Ubuntu and thence Mint.

I realize this was posted months ago... and this reference is years old - [me-tv is marked for autoremoval from testing](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755451#10).  You may already know all this, me-tv is otherwise retired from debian.  It's only available via sid as debports - "ports of packages to architectures not yet or not anymore available in Debian"
  I had found me-tv to be the most simplistic (utility wise) dvr program available and miss it dearly.  Although it no longer suits my needs, I am glad it still had some life - thanks!

**Comment by russel** [comment]
@dougK44883 I emailed the last known maintainer of the me-tv package in Debian some while back, but have heard nothing. I can only assume this means "not interested" – assuming anyone read the email. Once a few more issues with Me TV v3 are sorted, I may put in a new request to package. There is no point in doing this till the next release of GStreamer gets into Debian Sid though, so as to avoid hassles with version dependencies. It also depends on whether Glide goes for a request to package – Glide is a new Rust/GStreamer media player.
