### ISSUE TITLE
me-tv-schedule

### ISSUE THREAD

**Issue by dougK44883** [Me-TV/Me-TV#33]
Moving on to the next logical step, me-tv-schedule  ...can't make it easy all the time (ever actually)

First I was just going to suggest the help line for time 
`-s, --start-time <TIME>    Sets the start time of recording, ISO8601 format, no default.`
provide more of a mask or example.  To meager users, ISO =-8601 format is meaningless :(   I found this to be 24hour HH:MM.  If you want to go international (from your perspective), ~~stoopid americans~~ some regions will never figure out _yyyy-mm-dd_ on their own - that's just messed up to some.

Beyond a suggestion - more struggles... with the time no less.
```
dj@htpc:~$ me-tv-schedule --channel 11.2 --duration 5 --start-time 13:30 --output /media/dvr/show2.mpeg
thread 'main' panicked at 'Could not parse start time.: "Parser Error: 13:30"', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Best I can speculate from line [189](https://github.com/Me-TV/Me-TV/blob/ea2799331fed2cfc9710bba3ac028dae2fa50b0d/src/bin/me-tv-schedule.rs#L109) something about converting my time format?  Elsewhere I found, what I believe you're building `at` command line you use [%H:%M](https://github.com/Me-TV/Me-TV/blob/ea2799331fed2cfc9710bba3ac028dae2fa50b0d/src/bin/me-tv-schedule.rs#L159) I looked up [time/date strings](http://man7.org/linux/man-pages/man3/strftime.3.html) to confirm my 9:30am is 09:30 

[me-tv-schedule.rust_backtrace.TXT](https://github.com/Me-TV/Me-TV/files/2716486/me-tv-schedule.rust_backtrace.TXT)

**Comment by russel** [comment]
World dates and times are probably the biggest thing stopping the arrival of world peace. :-)

What I put in place was the fastest thing I could put in place that worked. My belief that ISO8601 is the One True Date and Time System is clearly evident. However, a program should work as users (rather than author) need it to. I think the `at` side of things probably is OK since it ought to be hidden from the user. The _me-tv-schedule_ command line is though a beast of a different colour (!).

I think the way forward is to use a Rust package that handles flexible date and time parsing and generates ISO8601 for internal checks and scheduling. I am not sure it currently exists though.

Of course `at` already has a very flexible time parser, and people can just use it directly with _me-tv-record_, _me-tv-schedule_ is in some sense totally redundant. However I think it is nice to have, when it can deal with dates and times as specified by general users.

**Comment by dougK44883** [comment]
Ok, so maybe I'm the dumb one, **_date_** time.  but adding a date 

```
--start-time 2018-12-29 10:38
error: Found argument '10:38' which wasn't expected, or isn't valid in this context
```
followed with a usage message   Tried adding a T to eliminate the space
```
--start-time 2018-12-29T10:38 --output /media/dvr/show2.mpeg
thread 'main' panicked at 'Failed to start at process.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
``` 
[me-tv-schedule.rust_backtrace2.TXT](https://github.com/Me-TV/Me-TV/files/2716518/me-tv-schedule.rust_backtrace2.TXT)
To confirm no typos (or device errors) I copied/pasted the text from the command line and executed `stat /media/dvr` successfully.

Tried single quote 
```
~$ me-tv-schedule --channel 11.2 --duration 5 --start-time '2018-12-29 10:57' --output /media/dvr/show2.mpeg
thread 'main' panicked at 'Could not parse start time.: "Parser Error: 2018-12-29 10:57"', libcore/result.rs:1009:5
note: Run with 'RUST_BACKTRACE=1' for a backtrace.
```
Double quotes - same thing.  
1) is start time complete date and time to start 
2) irregardless, how [censored] do you enter --start-time in ISO8601 format **?**

**Comment by russel** [comment]
2018-12-29T10:38 should have worked. That it didn't is a full on bug. '2018-12-29 10:57' should also have worked but is brittle because of the way shell and Rust command line system work so I can believe it fails.

**Comment by dougK44883** [comment]
> Of course `at` already has a very flexible time parser, and people can just use it directly with _me-tv-record_, _me-tv-schedule_ is in some sense totally redundant. However I think it is nice to have, when it can deal with dates and times as specified by general users.

I tend to agree.  Looking forward, although less than idea, using cron or cron.d for organization along with shell scripts to use me-tv-record.  Just wanted to try out the whole suit of applications.
It's a manual operation, for me, I tend to like to know what's going on.  Even with me-tv 1.4.x (1.3.7) it only recorded what/when you told it do, and named shows whatever you gave it.  I believe he added something like  $(date '+ - %a %b %d') to the file name for routine scheduling.

**Comment by russel** [comment]
I had a look at the at source code and the command line is parsed using a lex/yacc (or lex/bison) LALR(1) generated parser. I suspect the best way of doing something similar for me-tv-schedule is to use LALRPOP to create a command line parser. The difficulty is going to be specifying the information for at and the information for me-tv-record. Thinking caps on.

**Comment by russel** [comment]
I think I am going to take a different view and not do an parse as per `at`. Clearly time alone should imply today and I have added that. The question is what variants of dates for date-time to allow. Clearly ISO8601 (YYYY-MM-DD) is the one true way so that is in. But what others should be in at the risk of not educating people about ISO8601? :-)

**Comment by russel** [comment]
I have added just using a time (today assumed) as well as a date-time. I think though I am going to leave the ISO8601 format requirement in place and just extend the explanation in the help as needed to help people understand the command line. I shall close this issue for now as done, but knowing there will be some further changes required as we go on.
