### ISSUE TITLE
Please add ability to use remote control for volume. 

### ISSUE THREAD

**Issue by Randall-Glass** [Me-TV/Me-TV#41]
Please add ability to use remote control for volume.

**Comment by russel** [comment]
Hummm… volume change and channel change using a remote used to work. I just tried it for the first time in ages and the behaviour is not what it used to be, so there is a problem here. I am not sure what the problem is or how quickly it can be fixed, but debugged and fixed it will be.

**Comment by russel** [comment]
My problem is that there has been a breaking change in Linux regarding dynamic filenames. Now I have found that and corrected it for me, sound changing and channel changing by remote control works as I expected.

@Randall-Glass can you tell me what operating system you are using. Also which USB device/PCI device and remote control.

Update: My problem was not directly a Linux issue, it was indirectly a Linux issue, the real issue was a different of behaviour of the WinTV-dualHD USB device. The changes needed to make things work have been updated.

**Comment by Randall-Glass** [comment]
I am using Xenialpup64 (Puppy Linux)

It's a Puppy Linux version of Ubuntu 16.04.

I am using Hauppauge WinTV-HVR-950Q USB tuner.

__________________________
Best Regards!

Randall Glass
1412 W Boulevard St Apt 219
Marion, IL 62959
http://RadioTelephoneTutor.com


     On Saturday, April 4, 2020, 08:24:34 AM CDT, Russel Winder <notifications@github.com> wrote:  
 
 


My problem is that there has been a breaking change in Linux regarding dynamic filenames. Now I have found that and corrected it for me, sound changing and channel changing by remote control works as I expected.

@Randall-Glass can you tell me what operating system you are using. Also which USB device/PCI device and remote control.

**Comment by russel** [comment]
I am using a WinTV-soloHD with a pinnacle remote control and a WinTV-dualHD with a Hauppauge! remote control on Linux 5.4.19 and GStreamer 1.16.2 (Debian Sid packages as at 2020-04-05) with the Me TV 3.1 version from GitHub master compiled locally. These allow for sound and channel changing which is expected to work, and seems to work as expected. I tried a PC-TV 282e and a PC-TV 292e and although the pinnacle remote control works at the Linux level with both it doesn't seem to work with Me TV. I need to chase this up as they should both work as the Hauppauge! devices do. 

I am using DVB-T2 in Europe with no access to the ATSC of the USA, but I am assuming your WinTV-HVR-950Q is fundamentally equivalent to my WinTV-soloHD. If so it should work. Except…

…Ubuntu 16.04 uses (I believe) Linux 4.4 and has (I believe) GStreamer 1.8.2 as standard. Me TV 3.0.9 worked with GStreamer 1.14.3, I never had it working on GStreamer 1.8.2. I have done no work on the Me TV 3.0 series since starting on 3.1 which requires GStreamer 1.16.0 or later. The Travis-CI builds for Me TV 3.1 run on Xenial (with Linux 4.15 rather than the default), but I load GStreamer 1.16.1 rather than use the Xenial packages.

I forgot to ask which version of Me TV you were using. If I can get you to install GStreamer 1.16.1 then we should be able to get compiled executables from Travis-CI to you that should work as required.

**Comment by russel** [comment]
@Randall-Glass  I have released v3.0.10 which should work for you, though it is a bit of an experimental release – I am hopefully it works for everyone on GStreamer 1.14 but am ready to fix bugs and release v3.0.11 if that is not the case.

Executables available from Bintray https://bintray.com/beta/#/me-tv/Downloads/Me-TV/v3.0.10?tab=files

**Comment by russel** [comment]
On the grounds "it works for me", i.e. with my Hauppauge! WinTV-dualHD with Me TV v3.0.10 and master, the volume up and down, and channel up and down work as expected, I am going to close this issue. If it is still a problem for others, then either reopening this issue or opening a new issue will start investigations.
