### ISSUE TITLE
v3.0.9: Can't view channel that has space at the end of it's name

### ISSUE THREAD

**Issue by ljbade** [Me-TV/Me-TV#42]
For some reason `dvbv5-scan` produced a channel like this:
```
[WIN HD Canberra ]
	SERVICE_ID = 1939
	NETWORK_ID = 12915
	TRANSPORT_ID = 12922
	VIDEO_PID = 125
	AUDIO_PID = 525 725
	FREQUENCY = 219500000
	MODULATION = QAM/64
	BANDWIDTH_HZ = 7000000
	INVERSION = AUTO
	CODE_RATE_HP = 3/4
	CODE_RATE_LP = 1/2
	GUARD_INTERVAL = 1/16
	TRANSMISSION_MODE = 8K
	HIERARCHY = NONE
	DELIVERY_SYSTEM = DVBT
```

It seems the space at the end causes issues with errors like:
```
leith@leith-desktop:~/Me-TV/target/release$ GST_DEBUG=3 ./me-tv
Watch on /dev/ failed: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
Frontend Manager terminated.
0:00:04.099760441 19148 0x55f1b9814ef0 WARN              dvbbasebin parsechannels.c:900:set_properties_for_channel:<source> Problem finding information for channel 'WIN HD Canberra' in configuration file '/home/leith/.config/gstreamer-1.0/dvb-channels.conf'
0:00:04.099789688 19148 0x55f1b9814ef0 WARN                 GST_URI gsturi.c:668:gst_element_make_from_uri: source didn't accept URI 'dvb://WIN%20HD%20Canberra': Couldn't find details for channel 'WIN HD Canberra'
0:00:04.099865697 19148 0x55f1b9814ef0 WARN            uridecodebin gsturidecodebin.c:1415:gen_source_element:<uridecodebin0> error: Couldn't find details for channel 'WIN HD Canberra'
0:00:04.099872579 19148 0x55f1b9814ef0 WARN            uridecodebin gsturidecodebin.c:1415:gen_source_element:<uridecodebin0> error: No element accepted URI 'dvb://WIN%20HD%20Canberra'
```

I haven't tried a newer build as on Ubuntu 18.04 it is missing the newer gstreamer version needed.

**Comment by russel** [comment]
I feel this is a bug in dvbv5-scan. I wonder if it is worth sending in a bug report?

In terms of workaround, manually editing the ~/.config/gstreamer-1.0/dvb-channels.conf to change the "[WIN HD Canberra ]" to "[WIN HD Canberra]" should work.

There is an argument though that Me TV should cope with this situation. I haven't been maintaining the 3.0.x series, working instead on the 3.1.x series, though there hasn't been a release. Although the README says 3.1.x requires GStreamer 1.14.5, I think actually it needs 1.16.0 or later. I will investigate this. I never did get creation of executables working with Travis-CI and Bintray, perhaps I need to investigate whether I can get this done on GitLab using Ubuntu 18.04 so as to be able to provide further 3.0.x releases and Ubuntu 20.04 to provide 3.1.x releases for people.

**Comment by ljbade** [comment]
Yeah I will see if I can find where to report bugs to dvbv5-scan. I did fix it by manually editing the file. It might be worth having Me TV handle it though as I imagine people with older Linux distros won't get the bugfix for dvbv5-scan. Could be as simple as trimming white space at the end of string before comparison.

I also ended messing around with my copy the code to enable higher quality deinterlacing on GStreamer, first time I've touched rust so it's a bit messy but hopefully someone who is better at rust can tidy it up and add a config/menu setting for it.

**Comment by dougK44883** [comment]
The "reason" my not be dvbv5 fault.  If it's just a single channel, that's the info it recieved - for what ever (silly) reason.

It's been some time since I've run a scan, but looked through an old file.  I have one (a single) entry
``[Bounce ]``
with a trailing space in it's name.  I suspect it dues to who ever creates the EPG / Digital MPEG data (I don't know what it is) and maybe thought they... and forgot.
Several others all end as one might expect:
```
[Escape]
[WUPW TV]
[52.5]
[WBGUDT2]
```

Nevertheless, it's a text file and easily editable to what ever you want, and you can even change the order to suit your needs as well as remove entries you have no real use for.

Not being a developer, I can't say it's not a bug... but unless you have a space for each channel - it's probably saving the information as it receives it.

**Comment by russel** [comment]
Clearly some channel names for some transmitters have a trailing space, though none in the UK so I haven't had this problem myself. Traditionally in programming trailing space is insignificant and so gets removed. It may be though that dvbv5-scan takes the position of using the name as it comes, without removing trailing spaces. I think Me TV has to stay consistent with dvbv5-scan so as to avoid these conflicts.

I am in the process of getting the v3.0.x branch into a fit state to be able to to make new releases. Work on the master (currently thought of as 3.1.x) branch is slow and only the EPG stuff requires GStreamer 1.16.0, all other changes can be back-ported to the v3.0.x series and released since they only need GStreamer 1.14.0 which is what Ubuntu 18.04 has. Testing on Travis-CI (Ubuntu Bionic 18.04) and GitLab (Debian Buster, which has GStreamer 1.14.4) is working as required, the question is how to get the compiled executables for releases onto Bintray or somewhere else that people can download them from.

**Comment by SparksDJ** [comment]
On Fri, 2020-05-22 at 02:47 -0700, Russel Winder wrote:
> ... Testing on Travis-CI (Ubuntu Bionic 18.04) and GitLab (Debian
> Buster, which has GStreamer 1.14.4) is working as required ...

A fully-updated Debian Buster has GStreamer 1.16.2 .  I compiled a 
Me-Tv 3.1.x here almost exactly a year ago.  It took a long time to
find out what all the build-time dependencies were, and install them,
but the built program works (though it uses 100% CPU on one core, and
about 25% CPU on another).

**Comment by russel** [comment]
According to https://packages.debian.org Buster has GStreamer 1.14.4, which is actually very useful for me for testing – I can do all the 1.16.2 testing locally on Sid, what I need is the tests to pass on 1.14.0 and 1.14.4 which I choose not to be able to test locally. I am assuming you mean if you use buster-backports then you get 1.16.2 as per Bullseye and Sid. For the moment the EPG stuff in Me TV, which needs GStreamer 1.1.6.0 or later, isn't working. :-(

Me TV using that amount of CPU is worrying. On my laptop I see Me TV using between 10% and 60% of one CPU depending on how much work is needed at a particular time for the video and audio stream processing.
